### PR TITLE
Problem: upgrade to ethers 2.0 fails (fix #381)

### LINKED ISSUE #381: Problem: upgrade to ethers 2.0 fails
```
error[E0432]: unresolved import `ethers::prelude::FromErr`
[932](https://github.com/cronos-labs/play-cpp-sdk/actions/runs/4340839325/jobs/7579768543#step:5:933)
  --> wallet-connect/src/client.rs:23:25
[933](https://github.com/cronos-labs/play-cpp-sdk/actions/runs/4340839325/jobs/7579768543#step:5:934)
   |
[934](https://github.com/cronos-labs/play-cpp-sdk/actions/runs/4340839325/jobs/7579768543#step:5:935)
23 |         Address, Bytes, FromErr, JsonRpcClient, Middleware, NameOrAddress, Provider, ProviderError,
[935](https://github.com/cronos-labs/play-cpp-sdk/actions/runs/4340839325/jobs/7579768543#step:5:936)
   |                         ^^^^^^^ no `FromErr` in `prelude`
[936](https://github.com/cronos-labs/play-cpp-sdk/actions/runs/4340839325/jobs/7579768543#step:5:937)

[937](https://github.com/cronos-labs/play-cpp-sdk/actions/runs/4340839325/jobs/7579768543#step:5:938)
For more information about this error, try `rustc --explain E0432`.
```
https://github.com/cronos-labs/play-cpp-sdk/actions/runs/4340839325/jobs/7579768543

### PR DESCRIPTION
**Pull request by elecming**
👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest main? 
- [ ] Have you checked your code compiles? (`cargo build`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`cargo test`)
- [ ] Have you checked your code formatting is correct? (`cargo fmt -- --check --color=auto`)
- [ ] Have you checked your basic code style is fine? (`cargo clippy`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`cargo audit`)
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Review by leejw51crypto — APPROVED** [review]
lgtm

File: wallet-connect/src/client.rs [hunk 1]
```diff
@@ -235,10 +256,17 @@ pub enum WCError<M: Middleware> {
     ClientError(ClientError),
 }
 
-impl<M: Middleware> FromErr<M::Error> for WCError<M> {
-    fn from(src: M::Error) -> WCError<M> {
+impl<M: Middleware> MiddlewareError for WCError<M> {
+    type Inner = M::Error;
```
Comment (leejw51crypto) [inline wallet-connect/src/client.rs:260]: from_err, as_inner is pair, maybe add comment?

Comment (elecming) [reply wallet-connect/src/client.rs:260]: those are functions from ethers upgraded trait - MiddlewareError, document would be in the trait itself (if any).
