### PR TITLE
Problem: wallet connect tx legacy signing error with ethereum (fix #69)

### LINKED ISSUE #69: Problem: wallet connect tx legacy signing error with ethereum
`RlpExpectedToBeList`
in TransactionRequest::decode_signed_rlp

trust wallet (cronos) and test.walletconnect.org is ok,
only trust wallet (ethereum) not working

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution:
1. check the first bytes in tx_bytes
2. if in the range [0, 0x7f] : use TypedTransaction::decode_signed
3. if in the range [0xc0, 0xfe] : use TransactionRequest::decode_signed_rlp

### CODE REVIEW

**Comment by leejw51crypto** [comment]
checked with ethereum X trust wallet

File: wallet-connect/src/client.rs [hunk 1]
```diff
@@ -274,29 +273,22 @@ impl Middleware for WCMiddleware<Provider<Client>> {
...
-            TypedTransaction::Eip2930(_) => {
-                let decoded_request = Eip2930TransactionRequest::decode_signed_rlp(&tx_rlp);
-                decoded_request
-                    .map(|x| x.1)
-                    .map_err(|e| WCError::ClientError(ClientError::Eyre(eyre!(e))))
-            }
-            TypedTransaction::Legacy(_) => {
-                let decoded_request = TransactionRequest::decode_signed_rlp(&tx_rlp);
-                decoded_request
+        let signature = match tx_rlp.data() {
```
Comment (tomtau) [inline wallet-connect/src/client.rs]: good to keep the TODO note because there may be another bug 😁 
```suggestion
        // TODO: check that the decoded request matches the typed transaction content here? or a new `sign_transaction` function that returns both request+signature?
        let signature = match tx_rlp.data() {
```

**Review by tomtau — APPROVED** [review]
I haven't tested yet, but lgtm

**Comment by leejw51crypto** [comment]
test.walletconnect.org fixed

**Comment by leejw51crypto** [comment]
restore back range check

File: wallet-connect/src/client.rs [hunk 2]
```diff
@@ -274,29 +273,27 @@ impl Middleware for WCMiddleware<Provider<Client>> {
...
-                let decoded_request = TransactionRequest::decode_signed_rlp(&tx_rlp);
-                decoded_request
-                    .map(|x| x.1)
-                    .map_err(|e| WCError::ClientError(ClientError::Eyre(eyre!(e))))
-            }
-        }?;
 
-        Ok(signature)
+        // get first byte of tx_bytes
+        let first_byte = tx_bytes.to_vec()[0];
```
Comment (tomtau) [inline wallet-connect/src/client.rs]: should check that non-empty:
```suggestion
        let first_byte = match tx_rlp.data() {
            Ok(d) if !d.is_empty() => Ok(d[0]),
            _ => Err(WCError::ClientError(ClientError::Eyre(eyre!(
                "empty response data"
            )))),
        }?;

Comment (leejw51crypto) [reply wallet-connect/src/client.rs]: ok, i'll modify 
data() is not the first byte, test wallet didn't work
as_raw() is the raw bytes for rlp

should pick raw rlp bytes , which is the same with tx_bytes

**Comment by leejw51crypto** [comment]
return fail if rlp is empty

**Review by tomtau — APPROVED** [review]
