### PR TITLE
Problem: when trying to use sign legacy eth tx (fixes #64)

### LINKED ISSUE #64: Problem: when trying to use sign legacy eth tx
when using ethers,
` async fn sign_transaction`
 
doesn't work with this error below
```
sign_typed_transaction error Attempted to sign a transaction with no available signer. Hint: did you mean to use a SignerMiddleware
```

### PR DESCRIPTION
**Pull request by tomtau**
Solution: override sign_transaction

### CODE REVIEW

**Review by leejw51crypto — COMMENTED** [review]
change to vec![tx_obj]?
i think it will work

**Comment by leejw51crypto** [comment]
and data is not option,
instead of None,   info.data =Some(Bytes::from("".as_bytes().to_vec()));

working in trust wallet, but metamask not support yet

File: wallet-connect/src/client.rs [hunk 1]
```diff
@@ -221,15 +223,47 @@ impl<M: Middleware> FromErr<M::Error> for WCError<M> {
...
+            tx_obj.insert("gasPrice", format!("{:?}", gas_price));
+        }
+        if let Some(value) = tx.value() {
+            tx_obj.insert("value", format!("{:?}", value));
+        }
+        if let Some(nonce) = tx.nonce() {
+            tx_obj.insert("nonce", format!("{:?}", nonce));
+        }
+        self.0
+            .request("eth_signTransaction", vec![tx])
```
Comment (leejw51crypto) [inline wallet-connect/src/client.rs]: vec![tx_obj]

File: wallet-connect/src/client.rs [hunk 2]
```diff
@@ -221,15 +223,47 @@ impl<M: Middleware> FromErr<M::Error> for WCError<M> {
...
+        let mut tx_obj = HashMap::new();
+        tx_obj.insert("from", format!("{:?}", from));
+        if let Some(to) = tx.to() {
+            let addr = match to {
+                NameOrAddress::Address(addr) => *addr,
+                NameOrAddress::Name(n) => self.resolve_name(n).await?,
+            };
+            tx_obj.insert("to", format!("{:?}", addr));
+        }
+        if let Some(data) = tx.data() {
```
Comment (leejw51crypto) [inline wallet-connect/src/client.rs:249]: actualy, data field is mandatory,
if data is None, return error, here

Comment (leejw51crypto) [reply wallet-connect/src/client.rs:249]: or data is None, put as 
```
 info.data =Some(Bytes::from("".as_bytes().to_vec()));
 ```

Comment (leejw51crypto) [reply wallet-connect/src/client.rs:249]: trust wallet reject tx if data is None

**Review by leejw51crypto — APPROVED** [review]
lgtm
